import { id } from './id';

const ohif = {
  layout: '@ohif/extension-default.layoutTemplateModule.viewerLayout',
  sopClassHandler: '@ohif/extension-default.sopClassHandlerModule.stack',
  thumbnailList: '@ohif/extension-default.panelModule.seriesList',
  studyBrowser: '@ohif/extension-default.panelModule.studyBrowser',
};

const cornerstone = {
  viewport: '@ohif/extension-cornerstone.viewportModule.cornerstone',
};

// Segmentation extension for DICOM SEG (legacy mode)
// v3.11.0: polyseg (polymorphic-segmentation) is automatically initialized
// CONTOUR conversion happens in our extension via addSegmentationRepresentation
const segmentation = {
  sopClassHandler: '@ohif/extension-cornerstone-dicom-seg.sopClassHandlerModule.dicom-seg',
  panel: '@ohif/extension-cornerstone.panelModule.panelSegmentation',
};

// RT Structure Set extension for server-side contour rendering (RTSS mode)
// RTSS is generated by backend with pre-computed contours
// OHIF renders contours directly without WebAssembly conversion
const dicomRT = {
  sopClassHandler: '@ohif/extension-cornerstone-dicom-rt.sopClassHandlerModule.dicom-rt',
  viewport: '@ohif/extension-cornerstone-dicom-rt.viewportModule.dicom-rt',
};

const nerveAssessment = {
  uploadPanel: '@ohif/extension-nerve-assessment.panelModule.nerveUploadPanel',
  studyListPanel: '@ohif/extension-nerve-assessment.panelModule.nerveStudyListPanel',
  riskReportPanel: '@ohif/extension-nerve-assessment.panelModule.nerveRiskReportPanel',
  analysisPanel: '@ohif/extension-nerve-assessment.panelModule.analysisPanel',
  worklistLayout: '@ohif/extension-nerve-assessment.layoutTemplateModule.worklistLayout',
};

/**
 * Tool Group configuration for Nerve Assessment Mode
 * Based on OHIF v3.11.0 longitudinal mode initToolGroups.js
 *
 * Creates two tool groups:
 * - 'default': Standard stack viewport tools
 * - 'mpr': MPR-specific tools including Crosshairs for volume viewports
 */
function initToolGroup(
  extensionManager: any,
  toolGroupService: any,
  commandsManager: any,
  toolGroupId: string
) {
  // Get tool names from cornerstone extension (v3.11.0 pattern)
  const utilityModule = extensionManager.getModuleEntry(
    '@ohif/extension-cornerstone.utilityModule.tools'
  );

  if (!utilityModule?.exports) {
    console.error('[NerveAssessment Mode] Could not get cornerstone tools utility module');
    return;
  }

  const { toolNames, Enums } = utilityModule.exports;

  // Log available tool names for debugging
  console.log('[NerveAssessment Mode] Available toolNames:', Object.keys(toolNames || {}));

  // Build tools config, only including tools that exist
  const active: any[] = [];
  const passive: any[] = [];
  const enabled: any[] = [];
  const disabled: any[] = [];

  // Active tools with mouse bindings (OHIF v3.11.0 pattern)
  if (toolNames.WindowLevel) {
    active.push({
      toolName: toolNames.WindowLevel,
      bindings: [{ mouseButton: Enums.MouseBindings.Primary }],
    });
  }
  if (toolNames.Pan) {
    active.push({
      toolName: toolNames.Pan,
      bindings: [{ mouseButton: Enums.MouseBindings.Auxiliary }],
    });
  }
  if (toolNames.Zoom) {
    active.push({
      toolName: toolNames.Zoom,
      bindings: [{ mouseButton: Enums.MouseBindings.Secondary }, { numTouchPoints: 2 }],
    });
  }
  // StackScroll with wheel binding (v3.11.0 uses StackScroll, not StackScrollMouseWheel)
  if (toolNames.StackScroll) {
    active.push({
      toolName: toolNames.StackScroll,
      bindings: [{ mouseButton: Enums.MouseBindings.Wheel }, { numTouchPoints: 3 }],
    });
  }

  // Passive tools (available but not active by default)
  // Note: Crosshairs is NOT included here - it's only in MPR tool group
  const passiveToolNames = [
    'Length', 'ArrowAnnotate', 'Bidirectional', 'Probe',
    'EllipticalROI', 'CircleROI', 'RectangleROI', 'Angle', 'Magnify',
  ];
  const missingTools: string[] = [];
  for (const name of passiveToolNames) {
    if (toolNames[name]) {
      passive.push({ toolName: toolNames[name] });
    } else {
      missingTools.push(name);
    }
  }
  if (missingTools.length > 0) {
    console.warn('[NerveAssessment Mode] Missing tools:', missingTools);
  }

  // Enabled tools
  if (toolNames.ImageOverlayViewer) {
    enabled.push({ toolName: toolNames.ImageOverlayViewer });
  }
  if (toolNames.ReferenceLines) {
    enabled.push({ toolName: toolNames.ReferenceLines });
  }

  const tools = { active, passive, enabled, disabled };
  console.log('[NerveAssessment Mode] Creating tool group with tools:', {
    active: active.map(t => t.toolName),
    passive: passive.map(t => t.toolName),
    enabled: enabled.map(t => t.toolName),
  });

  toolGroupService.createToolGroupAndAddTools(toolGroupId, tools);
}

/**
 * Initialize MPR tool group - based on OHIF v3.11.0 longitudinal mode
 * Crosshairs is in disabled state with config, activated via toolbar
 */
function initMPRToolGroup(
  extensionManager: any,
  toolGroupService: any,
  commandsManager: any
) {
  const utilityModule = extensionManager.getModuleEntry(
    '@ohif/extension-cornerstone.utilityModule.tools'
  );

  if (!utilityModule?.exports) {
    console.error('[NerveAssessment Mode] Could not get cornerstone tools utility module for MPR');
    return;
  }

  const { toolNames, Enums } = utilityModule.exports;

  // Get cornerstoneViewportService for Crosshairs color config
  const serviceManager = extensionManager._servicesManager;
  const { cornerstoneViewportService } = serviceManager.services;

  const colorsByOrientation: Record<string, string> = {
    axial: 'rgb(200, 0, 0)',
    sagittal: 'rgb(200, 200, 0)',
    coronal: 'rgb(0, 200, 0)',
  };

  const tools = {
    active: [
      {
        toolName: toolNames.WindowLevel,
        bindings: [{ mouseButton: Enums.MouseBindings.Primary }],
      },
      {
        toolName: toolNames.Pan,
        bindings: [{ mouseButton: Enums.MouseBindings.Auxiliary }],
      },
      {
        toolName: toolNames.Zoom,
        bindings: [{ mouseButton: Enums.MouseBindings.Secondary }, { numTouchPoints: 2 }],
      },
      {
        toolName: toolNames.StackScroll,
        bindings: [{ mouseButton: Enums.MouseBindings.Wheel }, { numTouchPoints: 3 }],
      },
    ],
    passive: [
      { toolName: toolNames.Length },
      { toolName: toolNames.ArrowAnnotate },
      { toolName: toolNames.Bidirectional },
      { toolName: toolNames.DragProbe },
      { toolName: toolNames.Probe },
      { toolName: toolNames.EllipticalROI },
      { toolName: toolNames.CircleROI },
      { toolName: toolNames.RectangleROI },
      { toolName: toolNames.Angle },
      { toolName: toolNames.CobbAngle },
      { toolName: toolNames.Magnify },
      { toolName: toolNames.PlanarFreehandROI },
      { toolName: toolNames.SplineROI },
    ].filter(t => t.toolName), // Filter out undefined tools
    disabled: [
      {
        toolName: toolNames.Crosshairs,
        configuration: {
          viewportIndicators: true,
          viewportIndicatorsConfig: {
            circleRadius: 5,
            xOffset: 0.95,
            yOffset: 0.05,
          },
          disableOnPassive: true,
          autoPan: {
            enabled: false,
            panSize: 10,
          },
          getReferenceLineColor: (viewportId: string) => {
            const viewportInfo = cornerstoneViewportService?.getViewportInfo?.(viewportId);
            const viewportOptions = viewportInfo?.viewportOptions;
            if (viewportOptions) {
              return colorsByOrientation[viewportOptions.orientation] || '#0c0';
            }
            return '#0c0';
          },
        },
      },
      { toolName: toolNames.ReferenceLines },
    ].filter(t => t.toolName),
  };

  console.log('[NerveAssessment Mode] Creating MPR tool group');
  toolGroupService.createToolGroupAndAddTools('mpr', tools);
}

/**
 * Initialize Volume 3D tool group - based on OHIF v3.11.0 longitudinal mode
 * TrackballRotateTool as primary for 3D rotation
 */
function initVolume3DToolGroup(
  extensionManager: any,
  toolGroupService: any
) {
  const utilityModule = extensionManager.getModuleEntry(
    '@ohif/extension-cornerstone.utilityModule.tools'
  );

  if (!utilityModule?.exports) {
    console.error('[NerveAssessment Mode] Could not get cornerstone tools utility module for Volume3D');
    return;
  }

  const { toolNames, Enums } = utilityModule.exports;

  const tools = {
    active: [
      {
        toolName: toolNames.TrackballRotateTool,
        bindings: [{ mouseButton: Enums.MouseBindings.Primary }],
      },
      {
        toolName: toolNames.Zoom,
        bindings: [{ mouseButton: Enums.MouseBindings.Secondary }, { numTouchPoints: 2 }],
      },
      {
        toolName: toolNames.Pan,
        bindings: [{ mouseButton: Enums.MouseBindings.Auxiliary }, { numTouchPoints: 3 }],
      },
    ],
  };

  console.log('[NerveAssessment Mode] Creating Volume3D tool group');
  toolGroupService.createToolGroupAndAddTools('volume3d', tools);
}

/**
 * Toolbar button definitions for OHIF v3.11.0
 * Based on modes/longitudinal/src/toolbarButtons.ts
 */
const toolbarButtons = [
  // Measurement tools (split button)
  {
    id: 'MeasurementTools',
    uiType: 'ohif.toolButtonList',
    props: {
      groupId: 'MeasurementToolsGroupId',
      buttonSection: 'MeasurementTools',
    },
  },
  {
    id: 'Length',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-length',
      label: 'Length',
      tooltip: 'Length Tool',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  {
    id: 'Bidirectional',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-bidirectional',
      label: 'Bidirectional',
      tooltip: 'Bidirectional Tool',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  {
    id: 'Angle',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-angle',
      label: 'Angle',
      tooltip: 'Angle Tool',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  {
    id: 'EllipticalROI',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-elipse',
      label: 'Ellipse ROI',
      tooltip: 'Elliptical ROI Tool',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  {
    id: 'CircleROI',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-circle',
      label: 'Circle ROI',
      tooltip: 'Circle ROI Tool',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  // Window/Level (split button with presets)
  {
    id: 'WindowLevelTools',
    uiType: 'ohif.toolButtonList',
    props: {
      groupId: 'WindowLevelGroupId',
      buttonSection: 'WindowLevelTools',
    },
  },
  {
    id: 'WindowLevel',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-window-level',
      label: 'Window Level',
      tooltip: 'Drag to adjust W/L',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  {
    id: 'WL-SoftTissue',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-window-level',
      label: 'Soft Tissue',
      tooltip: 'W:350 / L:40',
      commands: {
        commandName: 'setWindowLevelPreset',
        commandOptions: { width: 350, level: 40 },
      },
    },
  },
  {
    id: 'WL-Bone',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-window-level',
      label: 'Bone',
      tooltip: 'W:2000 / L:500',
      commands: {
        commandName: 'setWindowLevelPreset',
        commandOptions: { width: 2000, level: 500 },
      },
    },
  },
  {
    id: 'WL-Lung',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-window-level',
      label: 'Lung',
      tooltip: 'W:1500 / L:-500',
      commands: {
        commandName: 'setWindowLevelPreset',
        commandOptions: { width: 1500, level: -500 },
      },
    },
  },
  {
    id: 'WL-Brain',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-window-level',
      label: 'Brain',
      tooltip: 'W:80 / L:40',
      commands: {
        commandName: 'setWindowLevelPreset',
        commandOptions: { width: 80, level: 40 },
      },
    },
  },
  // Pan
  {
    id: 'Pan',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-move',
      label: 'Pan',
      tooltip: 'Pan',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  // Zoom
  {
    id: 'Zoom',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-zoom',
      label: 'Zoom',
      tooltip: 'Zoom',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  // Stack Scroll
  {
    id: 'StackScroll',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-stack-scroll',
      label: 'Stack Scroll',
      tooltip: 'Stack Scroll',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  // 3D Rotate (Trackball) - only works in volume3d viewports
  {
    id: 'TrackballRotateTool',
    uiType: 'ohif.toolButton',
    props: {
      type: 'tool',
      icon: 'tool-3d-rotate',
      label: '3D Rotate',
      tooltip: '3D Rotate (Drag to rotate volume)',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['volume3d'] },
      },
      evaluate: {
        name: 'evaluate.cornerstoneTool',
        disabledText: 'Select a 3D viewport to enable this tool',
      },
    },
  },
  // Magnify
  {
    id: 'Magnify',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-magnify',
      label: 'Magnify',
      tooltip: 'Magnify',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  // Arrow Annotate
  {
    id: 'ArrowAnnotate',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-annotate',
      label: 'Arrow Annotate',
      tooltip: 'Arrow Annotate',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr', 'default'] },
      },
      evaluate: 'evaluate.cornerstoneTool',
    },
  },
  // Reset
  {
    id: 'Reset',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-reset',
      label: 'Reset View',
      tooltip: 'Reset View',
      commands: 'resetViewport',
    },
  },
  // Flip Horizontal
  {
    id: 'FlipHorizontal',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-flip-horizontal',
      label: 'Flip H',
      tooltip: 'Flip Horizontal',
      commands: 'flipViewportHorizontal',
    },
  },
  // Rotate Right
  {
    id: 'RotateRight',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-rotate-right',
      label: 'Rotate',
      tooltip: 'Rotate Right',
      commands: 'rotateViewportCW',
    },
  },
  // Invert
  {
    id: 'Invert',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-invert',
      label: 'Invert',
      tooltip: 'Invert',
      commands: 'invertViewport',
    },
  },
  // Cine
  {
    id: 'Cine',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'tool-cine',
      label: 'Cine',
      tooltip: 'Cine Player',
      commands: 'toggleCine',
    },
  },
  // Crosshairs (MPR only) - based on OHIF v3.11.0
  {
    id: 'Crosshairs',
    uiType: 'ohif.toolButton',
    props: {
      type: 'tool',
      icon: 'tool-crosshair',
      label: 'Crosshairs',
      tooltip: 'Crosshairs (MPR only)',
      commands: {
        commandName: 'setToolActiveToolbar',
        commandOptions: { toolGroupIds: ['mpr'] },
      },
      evaluate: {
        name: 'evaluate.cornerstoneTool',
        disabledText: 'Select an MPR viewport to enable this tool',
      },
    },
  },
  // MPR (Multi-planar reconstruction)
  {
    id: 'MPR',
    uiType: 'ohif.toolButton',
    props: {
      icon: 'icon-mpr',
      label: 'MPR',
      tooltip: 'Multi-planar Reconstruction',
      commands: {
        commandName: 'toggleHangingProtocol',
        commandOptions: {
          protocolId: 'mpr',
        },
      },
    },
  },
  // Layout options
  {
    id: 'Layout',
    uiType: 'ohif.layoutSelector',
    props: {
      rows: 3,
      columns: 4,
    },
  },
];

/**
 * Setup toolbar buttons using OHIF v3.11.0 API
 * - toolbarService.register() instead of addButtons()
 * - toolbarService.updateSection() for section configuration
 */
function setupToolbar(toolbarService: any) {
  // Register all toolbar buttons (v3.11.0 API)
  toolbarService.register(toolbarButtons);

  // Configure primary toolbar section
  // v3.11.0 uses updateSection with sections object
  const primaryButtonIds = [
    'MeasurementTools',
    'WindowLevelTools',
    'Pan',
    'Zoom',
    'Crosshairs',
    'ArrowAnnotate',
    'Reset',
    'FlipHorizontal',
    'RotateRight',
    'Invert',
    'Cine',
    'Layout',
  ];

  // Update sections using v3.11.0 API
  if (toolbarService.sections?.primary) {
    toolbarService.updateSection(toolbarService.sections.primary, primaryButtonIds);
  } else if (toolbarService.updateSection) {
    // Fallback: try direct section name
    toolbarService.updateSection('primary', primaryButtonIds);
  }

  // Configure MeasurementTools button list
  const measurementToolIds = ['Length', 'Bidirectional', 'Angle', 'EllipticalROI', 'CircleROI'];
  if (toolbarService.sections?.MeasurementTools) {
    toolbarService.updateSection(toolbarService.sections.MeasurementTools, measurementToolIds);
  } else if (toolbarService.updateSection) {
    toolbarService.updateSection('MeasurementTools', measurementToolIds);
  }

  // Configure WindowLevelTools button list
  const windowLevelToolIds = ['WL-SoftTissue', 'WL-Bone', 'WL-Lung', 'WL-Brain'];
  if (toolbarService.sections?.WindowLevelTools) {
    toolbarService.updateSection(toolbarService.sections.WindowLevelTools, windowLevelToolIds);
  } else if (toolbarService.updateSection) {
    toolbarService.updateSection('WindowLevelTools', windowLevelToolIds);
  }

  console.log('[NerveAssessment Mode] Toolbar registered with v3.11.0 API');
}

/**
 * Nerve Assessment Mode for OHIF v3.11.0
 *
 * RTSS Mode (Default - Server-Side Contour Generation):
 * - Backend generates DICOM RT Structure Set with pre-computed 2D contours
 * - OHIF renders contours directly via @ohif/extension-cornerstone-dicom-rt
 * - Avoids WebAssembly memory limit (~1.1GB for 18+ segments)
 * - File size: ~10-50MB (vector contours vs ~600MB voxel data)
 *
 * Legacy SEG Mode (Optional):
 * - Uses polyseg (polymorphic-segmentation) for LABELMAP → CONTOUR conversion
 * - May cause memory issues with many segments
 *
 * Features:
 * - Full toolbar with measurement tools, navigation, and viewing controls
 * - Supports both RTSS and SEG rendering
 */
function modeFactory({ modeConfiguration }: { modeConfiguration: any }) {
  return {
    id,
    routeName: 'nerve-assessment',
    displayName: 'Nerve Assessment',

    isValidMode: function ({ modalities }) {
      // Always valid - accept all studies
      return {
        valid: true,
        description: 'Nerve Assessment mode for CT/RTSTRUCT visualization',
      };
    },

    routes: [
      // Viewer route FIRST - for viewing studies with segmentation support
      // OHIF uses routes[0], so this must be first!
      {
        path: 'nerve-assessment',
        layoutTemplate: ({ location, servicesManager }: { location: any; servicesManager: any }) => {
          return {
            id: ohif.layout,
            props: {
              // Series List (thumbnails) - 기본 viewer처럼 RTSTRUCT 클릭 가능
              leftPanels: [ohif.thumbnailList],
              rightPanels: [
                // segmentation.panel,  // DISABLED: OHIF PanelSegmentation incompatible with custom labelmap structure
                nerveAssessment.analysisPanel,  // Nerve Analysis Panel - Analyze 버튼
              ],
              leftPanelDefaultClosed: false,
              rightPanelDefaultClosed: false,
              viewports: [
                // MPR viewport - cornerstone handles 3 viewports automatically via mpr protocol
                // RTSS contours are overlaid via segmentation service (not displaySetsToDisplay)
                {
                  namespace: cornerstone.viewport,
                  displaySetsToDisplay: [
                    ohif.sopClassHandler,           // CT/Stack images
                    segmentation.sopClassHandler,   // DICOM SEG
                    // NOTE: dicomRT는 여기 넣으면 안됨! RTSTRUCT는 volume이 아니라 contour 데이터
                    // segmentation service를 통해 자동 overlay됨
                  ],
                },
              ],
            },
          };
        },
      },
      // Worklist route SECOND - Upload + Study List (no StudyInstanceUID required)
      // Note: This route requires StudyInstanceUIDs, so it won't work as a standalone worklist
      {
        path: 'worklist',
        layoutTemplate: ({ location, servicesManager }: { location: any; servicesManager: any }) => {
          return {
            id: nerveAssessment.worklistLayout,
            props: {
              leftPanels: [nerveAssessment.uploadPanel],
            },
          };
        },
      },
    ],

    // Extension configurations (object format required by OHIF)
    extensions: {
      '@ohif/extension-default': {},
      '@ohif/extension-cornerstone': {},
      '@ohif/extension-cornerstone-dicom-seg': {},  // DICOM SEG support (legacy mode)
      '@ohif/extension-cornerstone-dicom-rt': {},   // DICOM RT Structure Set support (RTSS mode)
      '@ohif/extension-nerve-assessment': {},
    },

    // Custom MPR + 3D hanging protocol - 2x2 layout with volume3d viewport
    // Enables Crosshairs tool, 3 MPR viewports + 1 3D viewport for Surface mesh
    // Uses simple protocol ID (matches hangingProtocol.ts id field)
    hangingProtocol: 'nerve-assessment-mpr',
    // Register CT, SEG, and RT SOP Class handlers
    // RT handler enables direct rendering of server-generated RTSS contours
    sopClassHandlers: [
      ohif.sopClassHandler,           // CT/Stack images
      segmentation.sopClassHandler,   // DICOM SEG (legacy mode)
      dicomRT.sopClassHandler,        // DICOM RT Structure Set (RTSS mode)
    ],

    hotkeys: [
      { commandName: 'incrementActiveViewport', label: 'Next Viewport', keys: ['right'] },
      { commandName: 'decrementActiveViewport', label: 'Previous Viewport', keys: ['left'] },
      { commandName: 'rotateViewportCW', label: 'Rotate Right', keys: ['r'] },
      { commandName: 'flipViewportHorizontal', label: 'Flip Horizontally', keys: ['h'] },
      { commandName: 'flipViewportVertical', label: 'Flip Vertically', keys: ['v'] },
      { commandName: 'scaleUpViewport', label: 'Zoom In', keys: ['+'] },
      { commandName: 'scaleDownViewport', label: 'Zoom Out', keys: ['-'] },
      { commandName: 'fitViewportToWindow', label: 'Zoom to Fit', keys: ['='] },
      { commandName: 'resetViewport', label: 'Reset', keys: ['space'] },
      { commandName: 'previousImage', label: 'Previous Image', keys: ['up'] },
      { commandName: 'nextImage', label: 'Next Image', keys: ['down'] },
      { commandName: 'setToolActive', commandOptions: { toolName: 'WindowLevel' }, label: 'Window Level', keys: ['w'] },
      { commandName: 'setToolActive', commandOptions: { toolName: 'Pan' }, label: 'Pan', keys: ['p'] },
      { commandName: 'setToolActive', commandOptions: { toolName: 'Zoom' }, label: 'Zoom', keys: ['z'] },
    ],

    onModeEnter: ({
      servicesManager,
      extensionManager,
      commandsManager,
    }: {
      servicesManager: any;
      extensionManager: any;
      commandsManager: any;
    }) => {
      console.log('[NerveAssessment Mode] Entering mode v3.11.0 (MPR + RTSS)');

      const {
        toolGroupService,
        toolbarService,
        segmentationService,
        customizationService,
        displaySetService,
      } = servicesManager.services;

      // Step 0: Add thumbnail menu items (Delete button for RTSTRUCT/SEG)
      // OHIF v3.11.0: ohif.menuContent uses commandsManager.runAsync(commands)
      // So we must use 'commands' string, not 'onClick' callback
      if (customizationService) {
        try {
          // Get existing menu items and add our delete option
          const existingItems = customizationService.getCustomization('studyBrowser.thumbnailMenuItems') || [];

          const deleteMenuItem = {
            id: 'deleteSeriesFromOrthanc',
            label: 'Delete from Orthanc',
            iconName: 'Delete',
            commands: 'deleteSeriesFromOrthanc',  // Registered in getCommandsModule.ts
          };

          // Set customization with existing items + our new delete item
          customizationService.setCustomizations(
            {
              'studyBrowser.thumbnailMenuItems': { $set: [...existingItems, deleteMenuItem] },
            },
            'mode'  // CustomizationScope.Mode
          );

          console.log('[NerveAssessment Mode] Thumbnail delete menu added');
        } catch (e: any) {
          console.warn('[NerveAssessment Mode] Failed to add thumbnail menu:', e?.message || e);
        }
      }

      // Step 1: Initialize tool groups
      if (toolGroupService) {
        try {
          // Initialize default tool group (for fallback/stack viewports)
          initToolGroup(extensionManager, toolGroupService, commandsManager, 'default');
          console.log('[NerveAssessment Mode] Default tool group initialized');

          // Initialize MPR tool group (for volume viewports with Crosshairs)
          initMPRToolGroup(extensionManager, toolGroupService, commandsManager);
          console.log('[NerveAssessment Mode] MPR tool group initialized');

          // Initialize Volume3D tool group (for 3D rotation)
          initVolume3DToolGroup(extensionManager, toolGroupService);
          console.log('[NerveAssessment Mode] Volume3D tool group initialized');
        } catch (e: any) {
          console.warn('[NerveAssessment Mode] Tool group initialization failed:', e?.message || e);
        }
      } else {
        console.warn('[NerveAssessment Mode] toolGroupService not available');
      }

      // Step 2: Setup toolbar buttons using v3.11.0 API
      if (toolbarService) {
        try {
          setupToolbar(toolbarService);
        } catch (e: any) {
          console.warn('[NerveAssessment Mode] Toolbar setup failed:', e?.message || e);
        }
      } else {
        console.warn('[NerveAssessment Mode] toolbarService not available');
      }

      // Step 3: Configure segmentation display style
      if (segmentationService?.setConfiguration) {
        try {
          segmentationService.setConfiguration({
            renderOutline: true,
            renderFill: true,
            outlineWidthActive: 2,
            outlineWidthInactive: 1,
            fillAlpha: 0.3,
            outlineAlpha: 1,
          });
          console.log('[NerveAssessment Mode] Segmentation style configured');
        } catch (e) {
          // Configuration API might differ in this version
        }
      }

      // Note: Labelmap loading is handled by extension's onModeEnter
    },

    onModeExit: ({
      servicesManager,
    }: {
      servicesManager: any;
    }) => {
      console.log('[NerveAssessment Mode] Exiting mode');

      const { toolGroupService, toolbarService } = servicesManager.services;

      // Destroy tool groups
      if (toolGroupService?.destroyToolGroup) {
        try {
          toolGroupService.destroyToolGroup('default');
        } catch (e) {
          // Tool group might not exist
        }
        try {
          toolGroupService.destroyToolGroup('mpr');
        } catch (e) {
          // Tool group might not exist
        }
        try {
          toolGroupService.destroyToolGroup('volume3d');
        } catch (e) {
          // Tool group might not exist
        }
      }

      // Reset toolbar (v3.11.0 API)
      if (toolbarService?.reset) {
        try {
          toolbarService.reset();
        } catch (e) {
          // Toolbar reset might fail
        }
      }
    },
  };
}

const mode = {
  id,
  modeFactory,
  extensionDependencies: [
    '@ohif/extension-default',
    '@ohif/extension-cornerstone',
    '@ohif/extension-cornerstone-dicom-seg',  // DICOM SEG extension (legacy mode)
    '@ohif/extension-cornerstone-dicom-rt',   // DICOM RT extension (RTSS mode)
    '@ohif/extension-nerve-assessment',
  ],
};

export default mode;
