name: dice_ce

_target_: monai.losses.DiceCELoss
include_background: false
to_onehot_y: true
softmax: true
reduction: mean
lambda_dice: 1.0
lambda_ce: 1.0
lambda_bce: 1.0  
smooth_nr: 1e-5
smooth_dr: 1e-5
batch: true  # nnUNet: batch_dice=True

boundary_weight: 0.0